### ISSUE TITLE
Python "TypeError: type of argument inline_policies [...] when running "cdk bootstrap"command

### ISSUE THREAD

**Issue by danielhidalg** [aws-samples/amazon-mwaa-workflow-demo#1]
Hi,

I've just tried instructions at https://aws.amazon.com/es/blogs/aws-spanish/construyendo-pipelines-de-datos-con-amazon-managed-workflows-for-apache-airflow-amazon-emr-aws-glue-y-amazon-athena/, but as you can see on attachment, when I reach step 3 command "cdk bootstrap", it returns:

"[...] TypeError: type of argument inline_policies must be one of (Mapping[str, aws_cdk.aws_iam.PolicyDocument], NoneType); got list instead"

[CDK_BOOTSTRAP_ERROR.txt](https://github.com/aws-samples/amazon-mwaa-workflow-demo/files/9996872/CDK_BOOTSTRAP_ERROR.txt)

**Comment by mirus2017** [comment]
I have the same problem:
$ cdk bootstrap
[WARNING] @aws-cdk/aws-ec2.SubnetType#PRIVATE is deprecated.
  use `PRIVATE_WITH_NAT`
  This API will be removed in the next major release.
[WARNING] @aws-cdk/aws-ec2.SubnetType#PRIVATE is deprecated.
  use `PRIVATE_WITH_NAT`
  This API will be removed in the next major release.
Traceback (most recent call last):
  File "app.py", line 14, in <module>
    data_lake = DataLakeStack(app, 'cdk-mwaa-s3')
  File "/home/ec2-user/environment/amazon-mwaa-workflow-demo/.env/lib64/python3.8/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
  File "/home/ec2-user/environment/amazon-mwaa-workflow-demo/cdk_mwaa_blogpost/DataLakeStack.py", line 54, in __init__
    glue_role = iam.Role(self, id='AWSGlueServiceRole-mwaa-demo-crawler',
  File "/home/ec2-user/environment/amazon-mwaa-workflow-demo/.env/lib64/python3.8/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
  File "/home/ec2-user/environment/amazon-mwaa-workflow-demo/.env/lib64/python3.8/site-packages/aws_cdk/aws_iam/__init__.py", line 11375, in __init__
    props = RoleProps(
  File "/home/ec2-user/environment/amazon-mwaa-workflow-demo/.env/lib64/python3.8/site-packages/aws_cdk/aws_iam/__init__.py", line 9183, in __init__
    check_type(argname="argument inline_policies", value=inline_policies, expected_type=type_hints["inline_policies"])
  File "/home/ec2-user/environment/amazon-mwaa-workflow-demo/.env/lib64/python3.8/site-packages/typeguard/__init__.py", line 757, in check_type
    checker_func(argname, value, expected_type, memo)
  File "/home/ec2-user/environment/amazon-mwaa-workflow-demo/.env/lib64/python3.8/site-packages/typeguard/__init__.py", line 558, in check_union
    raise TypeError('type of {} must be one of ({}); got {} instead'.
TypeError: type of argument inline_policies must be one of (Mapping[str, aws_cdk.aws_iam.PolicyDocument], NoneType); got list instead

Subprocess exited with error 1
